### ISSUE TITLE
Support Windows Terminal

### ISSUE THREAD

**Issue by FoxtrotSierra6829** [hetrodoo/hetrodo-node-hide-console-window-napi#4]
If the default terminal application is not set to windows console host but to windows terminal, the node application will start inside windows terminal which results in a secondary empty window which can be toggled hidden, but it does not have any effect on the real console window which is hosted inside windows terminal.

<details>
<summary>with windows terminal as default</summary>

https://user-images.githubusercontent.com/50082450/171955404-714519dc-df70-46d6-b4de-bb98c35a2b3c.mp4

</details>

<details>
<summary>with windows console host as default</summary>

https://user-images.githubusercontent.com/50082450/171955430-c4ac9e12-4d71-4e8a-acc3-33f9567b4cef.mp4

</details>

**Comment by popstas** [comment]
Similar issue in Windows Terminal project - https://github.com/microsoft/terminal/issues/12570

Fixed in https://github.com/microsoft/terminal/pull/12515

Windows Terminal Preview v1.14.143 now support window hide - https://apps.microsoft.com/store/detail/windows-terminal-preview/9N8G5RFZ9XK3?hl=ru-ru&gl=RU

I tried, it at way to work )

- Default Console: hide work
- Windows Terminal 1.11: hide not affects
- Windows Terminal 1.14: hide minimizes window

Video with Windows Terminal 1.14, then default console:

https://user-images.githubusercontent.com/3027126/172389156-6f482343-7a63-4b85-b3f7-d0e94ebdc9cd.mp4

**Comment by FoxtrotSierra6829** [comment]
Looks promising. Tho sadly they added this afterwards... https://github.com/microsoft/terminal/commit/997b4acce5b6de63f9414340ccdfa9b9e7bc2ad7
Hope they'll get it sorted
